In [1]:
import numpy as np  
# 'import' loads the library. 'as np' lets you write 'np' instead of typing 'numpy' every time.

x = np.array([10, 20, 30, 40]) 
# Creates a 1D list of numbers optimized for fast math operations.

print(x)        # Output: [10 20 30 40]
print(x.shape)  # Output: (4,) — Tells you the dimensions (4 elements in 1 dimension).
print(x.dtype)  # Output: int64 or int32 — Shows the data type (integers).

matrix = np.array([[1, 2, 3], [4, 5, 6]]) 
# Creates a 2D grid (2 rows, 3 columns).

print(matrix.shape) # Output: (2, 3) — 2 rows, 3 columns.

[10 20 30 40]
(4,)
int64
(2, 3)


In [2]:
# Vectorized Operations (Math performed on every single element automatically)
x = np.array([1, 2, 3, 4]) 
print(x * 10)  # Output: [10 20 30 40] — Multiplies every item by 10.
print(x + 5)   # Output: [6 7 8 9]     — Adds 5 to every item.

# Useful Helper Functions
np.zeros((2, 3))    # Creates a 2x3 matrix full of zeros.
np.ones((2, 3))     # Creates a 2x3 matrix full of ones.
np.arange(0, 10, 2) # Generates numbers from 0 up to (not including) 10, stepping by 2: [0, 2, 4, 6, 8].
np.mean(x)          # Calculates the average of array x.
np.std(x)           # Calculates the standard deviation of array x.
np.min(x) / np.max(x) # Returns the lowest/highest value in x.
x.reshape(2, 2)     # Changes a 1D array of 4 items into a 2x2 matrix.

[10 20 30 40]
[6 7 8 9]


array([[1, 2],
       [3, 4]])

In [3]:
import pandas as pd  
# Loads pandas with the standard shorthand 'pd'.

# Create a dictionary of data (column name -> list of values)
data = { 
    "name": ["Ali", "Sara", "Usman", "Hina"], 
    "age": [23, 24, 22, 25], 
    "score": [82, 91, 76, 88] 
} 

df = pd.DataFrame(data) # Converts the dictionary into a formatted table.

print(df.head())    # Displays the first 5 rows of the table.
print(df.shape)     # Displays the dimensions: (4, 3) -> 4 rows, 3 columns.
print(df.info())    # Summary of column names, data types, and non-null values.
print(df.describe())# Statistical summary (mean, min, max, std) for numerical columns.

    name  age  score
0    Ali   23     82
1   Sara   24     91
2  Usman   22     76
3   Hina   25     88
(4, 3)
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str  
 1   age     4 non-null      int64
 2   score   4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes
None
             age      score
count   4.000000   4.000000
mean   23.500000  84.250000
std     1.290994   6.652067
min    22.000000  76.000000
25%    22.750000  80.500000
50%    23.500000  85.000000
75%    24.250000  88.750000
max    25.000000  91.000000


In [3]:
import pandas as pd

data = { 
    "name": ["Ali", "Sara", "Usman", "Hina"], 
    "age": [23, 24, 22, 25], 
    "score": [82, 91, 76, 88] 
} 

df = pd.DataFrame(data)

# Selecting and Filtering
print(df["score"])             # Selects a single column ("score").
print(df[["name", "score"]])   # Selects multiple columns ("name" and "score").

high_scores = df[df["score"] >= 85] 
# Filters rows where 'score' is 85 or higher (Sara and Hina).
print(high_scores)

# Creating a Derived Column
df["passed"] = df["score"] >= 50 
# Adds a new column 'passed' containing True/False based on the score.
print(df)

0    82
1    91
2    76
3    88
Name: score, dtype: int64
    name  score
0    Ali     82
1   Sara     91
2  Usman     76
3   Hina     88
   name  age  score
1  Sara   24     91
3  Hina   25     88
    name  age  score  passed
0    Ali   23     82    True
1   Sara   24     91    True
2  Usman   22     76    True
3   Hina   25     88    True
